main: republicaEternityEventIII.republica.devteam.EternityMain
name: Eternity Event III
version: 0.0.1
authors: [xXProdigalXx, Perolan, mathphreak, Thosha]
commands:
  Ziminiar:
    description: Summon Ziminiar!
  Caesar:
    description: Drop messages from Caesar.
  testSFX:
    description: Test sound effects.